spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    org:
      hibernate:
        SQL: debug

s3:
  accessKey: minio
  secretKey: miniopass
  region: ap-northeast-1
  endPoint: http://localhost:9000