spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://trialdb.cmwjevpdlfsq.ap-northeast-1.rds.amazonaws.com:1433;databaseName=trial;encrypt=true;trustServerCertificate=true
    username: sa
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    org:
      hibernate:
        SQL: debug
    com:
      zaxxer:
        hikari: debug

s3:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  region: ap-northeast-1
  endPoint: https://s3-ap-northeast-1.amazonaws.com