spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://testdb.cmwjevpdlfsq.ap-northeast-1.rds.amazonaws.com:1433;databaseName=testdb
    username: sa
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    org:
      hibernate:
        SQL: debug
    com:
      zaxxer:
        hikari: debug

s3:
  accessKey: minio
  secretKey: miniopass
  region: ap-northeast-1
  endPoint: http://localhost:9000